# Generated by Django 3.2.8 on 2022-03-07 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=225, null=True, verbose_name='موضوع')),
                ('text', models.TextField(null=True, verbose_name='متن پیامک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('recipients', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='گیرندگان')),
                ('recipients_roles', models.ManyToManyField(blank=True, to='accounts.Role', verbose_name='گیرندگان')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک ها',
                'ordering': ('created_at',),
            },
        ),
    ]
