# Generated by Django 3.2.8 on 2021-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsms',
            name='text',
            field=models.TextField(null=True, verbose_name='متن پیامک'),
        ),
        migrations.AlterField(
            model_name='sendsms',
            name='topic',
            field=models.CharField(max_length=225, null=True, verbose_name='موضوع'),
        ),
    ]
