# Generated by Django 3.2.8 on 2021-10-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20211028_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsms',
            name='sms_type',
            field=models.CharField(choices=[('1', 'عمومی'), ('2', 'شخصی')], default='1', help_text='اگر در متن پیامک متغیر نسبت به کاربر وجود دارد گزینه شخصی اتخاب شود و در غیر اینصورت گزینه عمومی', max_length=10, verbose_name='نوع پیام'),
        ),
    ]
