# Generated by Django 3.2.8 on 2022-03-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profilecompletionpoints_options'),
        ('sms', '0003_sendsms_sms_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsms',
            name='recipients_roles',
            field=models.ManyToManyField(to='accounts.Role', verbose_name='گیرندگان'),
        ),
    ]
