# Generated by Django 3.2.8 on 2022-03-03 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profilecompletionpoints_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0004_sendsms_recipients_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsms',
            name='recipients',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='گیرندگان'),
        ),
        migrations.AlterField(
            model_name='sendsms',
            name='recipients_roles',
            field=models.ManyToManyField(blank=True, to='accounts.Role', verbose_name='گیرندگان'),
        ),
    ]
