# Generated by Django 3.2.8 on 2022-03-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20220304_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsms',
            name='sms_type',
        ),
    ]
