version: "3.8"


services:


  redis:
    image: redis:alpine
    container_name: redis
    ports:
    - "6379:6379"

    networks:
      forum_net:
        ipv4_address: 192.168.0.2


  db:
    image: postgres
    volumes:
    - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    - ./db:/var/lib/postgresql/data

    container_name: postgres_db

    ports:
      - "5432:5432"


    networks:
      forum_net:
        ipv4_address: 192.168.0.3


  app:
    build:
      context: .
    volumes:
    - .:/ehyasalamat
    - static:/ehyasalamat/static
    - media:/ehyasalamat/media
    ports:
    - 8000:8000
    depends_on:
      - db
    networks:
      forum_net:
        ipv4_address: 192.168.0.4
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
    - "5050:80"
    networks:
      forum_net:
        ipv4_address: 192.168.0.5


  proxy:
    build: ./nginx
    ports:
    - "80:80"

    volumes:
    - static:/static
    - media:/media
    networks:
      forum_net:
        ipv4_address: 192.168.0.6

    depends_on:
      - app
    restart: on-failure

networks:
  forum_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"


volumes:
  static:
  media:
