version: "3.7"


services:


  redis:
    image: redis:alpine
    container_name: ehya_redis
    ports:
      - "6379:6379"

    networks:
      forum_net:
        ipv4_address: 192.167.0.2


  db:
    image: postgres
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: ehya_postgres_db

    ports:
      - "5432:5432"


    networks:
      forum_net:
        ipv4_address: 192.167.0.3


  app:
    build:
      context: .
    volumes:
      - .:/ehyasalamat
      - static:/ehyasalamat/static
      - media:/ehyasalamat/media
    ports:
      - 8000:8000
    container_name: Ehya
    depends_on:
      - db
    networks:
      forum_net:
        ipv4_address: 192.167.0.4
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: EhyapgAdmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
      - "5050:80"
    networks:
      forum_net:
        ipv4_address: 192.167.0.5


  proxy:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - static:/static
      - media:/media
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    networks:
      forum_net:
        ipv4_address: 192.167.0.6

    depends_on:
      - app
    restart: on-failure

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email doom_horn@yahoo.com -d atabakhooshangi.ir --agree-tos
networks:
  forum_net:
    ipam:
      driver: default
      config:
        - subnet: 192.167.0.0/24


volumes:
  static:
  media:
