# Generated by Django 3.2.8 on 2021-12-20 10:59

from django.db import migrations, models
import treasure.models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_treasureanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=treasure.models.upload_location, validators=[treasure.models.file_size], verbose_name='فایل ارسالی'),
        ),
    ]
