# Generated by Django 3.2.8 on 2022-03-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import push_notification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=True, verbose_name='خانه')),
                ('inform', models.BooleanField(default=True, verbose_name='اعلانات')),
                ('support', models.BooleanField(default=True, verbose_name='پشتیبانی')),
                ('ticket', models.BooleanField(default=True, verbose_name='پرس و پاسخ')),
            ],
            options={
                'verbose_name': 'بخش های پوش نتیفیکیشن',
                'verbose_name_plural': 'بخش های پوش نتیفیکیشن',
            },
        ),
        migrations.CreateModel(
            name='SendPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to=push_notification.models.upload_location, verbose_name='تصویر')),
                ('inf_type', models.CharField(choices=[('1', 'شخصی'), ('2', 'عمومی'), ('3', 'اختصاصی')], default='2', max_length=2, verbose_name='نوع')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('roles', models.ManyToManyField(blank=True, to='accounts.Role', verbose_name='نقش های گیرندگان')),
                ('user', models.ForeignKey(blank=True, help_text='اگر نوع اطلاعیه شخصی باشد نیاز است کاربر مخاطب مشخص شود', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مخاطب')),
            ],
            options={
                'verbose_name': 'ارسال پوش نوتیفیکیشن',
                'verbose_name_plural': 'ارسال پوش نوتیفیکیشن',
            },
        ),
    ]
