# Generated by Django 3.2.8 on 2022-02-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotificationsections',
            name='treasure',
        ),
    ]
