# Generated by Django 3.2.8 on 2022-02-27 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_notification', '0002_remove_pushnotificationsections_treasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('send_to_all', models.BooleanField(default=False, help_text='اگر انتخاب شود این پوش نوتیفیکیشن به تمام کاربران اپلیکیشن ارسال خواهد شد.', verbose_name='ارسال همگانی')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('receptors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='گیرندگان')),
            ],
            options={
                'verbose_name': 'ارسال پوش نوتیفیکیشن',
                'verbose_name_plural': 'ارسال پوش نوتیفیکیشن',
            },
        ),
    ]
