# Generated by Django 3.2.8 on 2022-02-28 21:36

from django.db import migrations, models
import push_notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0003_sendpush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendpush',
            name='image',
            field=models.ImageField(upload_to=push_notification.models.upload_location, verbose_name='تصویر'),
        ),
    ]
