# Generated by Django 3.2.8 on 2022-03-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profilecompletionpoints_options'),
        ('push_notification', '0004_alter_sendpush_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendpush',
            name='send_to_all',
        ),
        migrations.AddField(
            model_name='sendpush',
            name='inf_type',
            field=models.CharField(choices=[('1', 'شخصی'), ('2', 'عمومی'), ('3', 'اختصاصی')], default='2', max_length=2, verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='sendpush',
            name='roles',
            field=models.ManyToManyField(blank=True, to='accounts.Role', verbose_name='نقش های گیرندگان'),
        ),
    ]
