# Generated by Django 3.2.8 on 2022-03-06 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_notification', '0005_auto_20220306_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendpush',
            name='receptors',
        ),
        migrations.AddField(
            model_name='sendpush',
            name='user',
            field=models.ForeignKey(blank=True, help_text='اگر نوع اطلاعیه شخصی باشد نیاز است کاربر مخاطب مشخص شود', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مخاطب'),
        ),
    ]
