# Generated by Django 3.2.8 on 2021-11-05 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCompletionPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0, help_text='بعد از تکمیل پروفایل این مقدار امتیاز به کاربر توسط کاربر کسب میشود', verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'امتیاز اولبه',
                'verbose_name_plural': 'امتیاز اولبه',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=65, null=True, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='شماره تلفن همراه')),
                ('role', models.CharField(choices=[('1', 'عضو عادی'), ('2', 'عضو فعال'), ('3', 'کارشناس'), ('4', 'کارشناس ارشد'), ('5', 'مدیر'), ('6', 'مدیر ارشد'), ('7', 'دانشجو'), ('8', 'استاد'), ('9', 'حکیم'), ('10', 'عضو جامعه'), ('11', 'شورای مرکزی'), ('12', 'مراجعین مطب'), ('13', 'مدیر کل')], default=1, max_length=20, verbose_name='نوع عضویت')),
                ('first_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='نام خانوادگی')),
                ('province', models.CharField(blank=True, max_length=40, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='شهر')),
                ('birthday', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('degree', models.CharField(blank=True, max_length=30, null=True, verbose_name='مدرک تحصیلی')),
                ('field_of_study', models.CharField(blank=True, max_length=60, null=True, verbose_name='رشته تحصیلی')),
                ('job', models.CharField(blank=True, max_length=60, null=True, verbose_name='شغل')),
                ('points', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('profile_completion_point', models.CharField(choices=[('1', 'کسب شده'), ('2', 'کسب نشده')], default='2', max_length=1, verbose_name='امتیاز تکمیل پروفایل')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='آدرس آی پی')),
                ('verify_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد احراز')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref', to=settings.AUTH_USER_MODEL, verbose_name='معرف')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('user_referrals', models.ManyToManyField(blank=True, related_name='urefs', to=settings.AUTH_USER_MODEL, verbose_name='معرفی کرده')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
                'ordering': ('date_joined',),
            },
        ),
    ]
