# Generated by Django 3.2.8 on 2021-10-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'عضو عادی'), ('2', 'عضو فعال'), ('3', 'کارشناس'), ('4', 'کارشناس ارشد'), ('5', 'مدیر'), ('6', 'مدیر ارشد'), ('7', 'دانشجو'), ('8', 'استاد'), ('9', 'حکیم'), ('10', 'عضو جامعه'), ('11', 'شورای مرکزی'), ('12', 'مراجعین مطب'), ('13', 'مدیر کل')], default=1, max_length=20, verbose_name='نوع عضویت'),
        ),
    ]
