# Generated by Django 3.2.8 on 2021-10-17 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211015_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref', to=settings.AUTH_USER_MODEL, verbose_name='معرف'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_referrals',
            field=models.ManyToManyField(blank=True, null=True, related_name='urefs', to=settings.AUTH_USER_MODEL, verbose_name='معرفی کرده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
    ]
