# Generated by Django 3.2.8 on 2021-10-17 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211018_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_referrals',
            field=models.ManyToManyField(blank=True, related_name='urefs', to=settings.AUTH_USER_MODEL, verbose_name='معرفی کرده'),
        ),
    ]
