# Generated by Django 3.2.8 on 2021-10-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_user_referrals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('date_joined',), 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
    ]
