# Generated by Django 3.2.8 on 2021-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_expert',
            field=models.BooleanField(default=False, verbose_name='ارشد'),
        ),
    ]
