# Generated by Django 3.2.8 on 2021-12-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_is_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=75, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], default='', max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=75, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='استان'),
        ),
    ]
