# Generated by Django 3.2.8 on 2022-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211228_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=5, help_text='مقدار امتیاز اهدایی جهت استفاده بیش از 5 دقیقه از اپلیکیشن', verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'امتیاز فعالیت',
                'verbose_name_plural': 'امتیاز فعالیت',
            },
        ),
    ]
