# Generated by Django 3.2.8 on 2022-02-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_activitypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False, help_text='نشان میدهد آیا اپلیکیشن برروزرسانی دارد یا خیر', verbose_name='دارد')),
            ],
            options={
                'verbose_name': 'برروزرسانی',
                'verbose_name_plural': 'برروزرسانی',
            },
        ),
    ]
