# Generated by Django 3.2.8 on 2022-02-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220220_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_support',
        ),
    ]
