# Generated by Django 3.2.8 on 2022-02-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_is_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='appupdate',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک آپدیت'),
        ),
    ]
