# Generated by Django 3.2.8 on 2022-03-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_pointgainhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitypoint',
            options={'verbose_name': 'امتیاز فعالیت (تنظیمات)', 'verbose_name_plural': 'امتیاز فعالیت (تنظیمات)'},
        ),
        migrations.AlterModelOptions(
            name='appupdate',
            options={'verbose_name': 'برروزرسانی (تنظیمات)', 'verbose_name_plural': 'برروزرسانی (تنظیمات)'},
        ),
        migrations.AlterModelOptions(
            name='profilecompletionpoints',
            options={'verbose_name': 'امتیاز اولبه (تنظیمات)', 'verbose_name_plural': 'امتیاز اولبه (تنظیمات)'},
        ),
    ]
