# Generated by Django 3.2.8 on 2022-03-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220303_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecompletionpoints',
            options={'verbose_name': 'امتیاز اولبه  (تنظیمات)', 'verbose_name_plural': 'امتیاز اولبه (تنظیمات)'},
        ),
    ]
