# Generated by Django 3.2.8 on 2022-03-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profilecompletionpoints_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appupdate',
            options={'ordering': ('value',), 'verbose_name': 'برروزرسانی (تنظیمات)', 'verbose_name_plural': 'برروزرسانی (تنظیمات)'},
        ),
        migrations.AlterModelOptions(
            name='pointgainhistory',
            options={'ordering': ('date_created',), 'verbose_name': 'تاریخجه کسب امتیاز', 'verbose_name_plural': 'تاریخجه های کسب امتیاز'},
        ),
    ]
