# Generated by Django 3.2.8 on 2022-03-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220304_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=5, help_text='مقدار امتیاز اهدایی جهت دعوت از دوستان', verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'امتیاز معرفی (تنظیمات)',
                'verbose_name_plural': 'امتیاز معرفی (تنظیمات)',
            },
        ),
    ]
