# Generated by Django 3.2.8 on 2022-03-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_referralpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralpoint',
            name='value',
            field=models.PositiveIntegerField(default=10, help_text='مقدار امتیاز اهدایی جهت دعوت از دوستان', verbose_name='مقدار'),
        ),
    ]
