# Generated by Django 3.2.8 on 2022-03-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_referralpoint_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecompletionpoints',
            options={'verbose_name': 'امتیاز تکمیل پروفایل  (تنظیمات)', 'verbose_name_plural': 'امتیاز تکمیل پروفایل (تنظیمات)'},
        ),
    ]
