# Generated by Django 3.2.8 on 2022-03-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profilecompletionpoints_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_answer_limit', models.PositiveSmallIntegerField(default=6, verbose_name='محدودیت تعداد پاسخ تیکت')),
                ('ticket_cost', models.PositiveSmallIntegerField(default=5, verbose_name='هزینه پرسش از طریق تیکت')),
                ('comment_point', models.PositiveSmallIntegerField(default=1, verbose_name='امتیاز ثبت کامنت')),
                ('support_answer_limit', models.PositiveSmallIntegerField(default=6, verbose_name='محدودیت تعداد پاسخ تیکت پشتیبانی')),
                ('profile_completion_point', models.PositiveSmallIntegerField(default=10, verbose_name='امتیاز تکمیل پروفایل')),
                ('activity_point', models.PositiveSmallIntegerField(default=1, verbose_name='امتیاز فعالیت')),
                ('referral_point', models.PositiveSmallIntegerField(default=10, verbose_name='امتیاز معرفی دوستان')),
            ],
            options={
                'verbose_name': 'تنظیمات اپلیکیشن',
                'verbose_name_plural': 'تنظیمات اپلیکیشن',
            },
        ),
    ]
