# Generated by Django 3.2.8 on 2022-03-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام بخش')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('associated_roles', models.ManyToManyField(blank=True, to='accounts.Role', verbose_name='نقش های مربوطه')),
            ],
            options={
                'verbose_name': 'بخش پشتیبانی',
                'verbose_name_plural': 'بخش های پشتیبانی',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='موضوع')),
                ('request_text', models.TextField(blank=True, verbose_name='متن درخواست')),
                ('status_for_user', models.CharField(choices=[('1', 'در حال بررسی'), ('2', 'پاسخ داده شده'), ('3', 'بسته شده')], default=1, max_length=1, verbose_name='وضعیت برای کاربر')),
                ('status_for_support', models.CharField(choices=[('1', 'جدید'), ('2', 'پاسخ داده شده'), ('3', 'بسته شده'), ('4', 'پاسخ کاربر')], default=1, max_length=1, verbose_name='وضعیت برای پشتیبان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportsection', verbose_name='بخش مربوطه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت پشتیانی',
                'verbose_name_plural': 'تیکت های پشتیبانی',
                'ordering': ('created_at', 'topic'),
            },
        ),
        migrations.CreateModel(
            name='SupportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پاسخ')),
                ('status', models.CharField(choices=[('1', 'دیده شده'), ('2', 'دیده نشده')], default=2, max_length=1, verbose_name='وضعیت')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دیده شدن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportticket', verbose_name='تیکت پشتیبانی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پاسخ پشتیبانی',
                'verbose_name_plural': 'پاسخ های پشتیبانی',
                'ordering': ('created_at',),
            },
        ),
    ]
