# Generated by Django 3.2.8 on 2021-11-11 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='موضوع')),
                ('request_text', models.TextField(blank=True, verbose_name='متن درخواست')),
                ('status', models.CharField(choices=[('1', 'جدید'), ('2', 'در حال بررسی'), ('3', 'پاسخ داده شده'), ('4', 'پاسخ کاربر'), ('5', 'بسته شده')], default=1, max_length=1, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت پشتیانی',
                'verbose_name_plural': 'تیکت های پشتیبانی',
                'ordering': ('created_at', 'topic'),
            },
        ),
    ]
