# Generated by Django 3.2.8 on 2021-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticketanswerlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='status',
        ),
        migrations.AddField(
            model_name='supportanswer',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دیده شدن'),
        ),
        migrations.AddField(
            model_name='supportanswer',
            name='status',
            field=models.CharField(choices=[('1', 'دیده شده'), ('2', 'دیده نشده')], default=2, max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status_for_support',
            field=models.CharField(choices=[('1', 'جدید'), ('2', 'پاسخ داده شده'), ('3', 'بسته شده'), ('4', 'پاسخ کاربر')], default=1, max_length=1, verbose_name='وضعیت برای پشتیبان'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status_for_user',
            field=models.CharField(choices=[('1', 'در حال بررسی'), ('2', 'پاسخ داده شده'), ('3', 'بسته شده')], default=1, max_length=1, verbose_name='وضعیت برای کاربر'),
        ),
    ]
