# Generated by Django 3.2.8 on 2021-12-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_supportticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportanswer',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportticket', verbose_name='تیکت پشتیبانی'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportsection', verbose_name='بخش مربوطه'),
        ),
    ]
