# Generated by Django 3.2.8 on 2021-10-22 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(choices=[('1', 'عضو عادی'), ('2', 'عضو فعال'), ('3', 'کارشناس'), ('4', 'کارشناس ارشد'), ('5', 'مدیر'), ('6', 'مدیر ارشد'), ('7', 'دانشجو'), ('8', 'استاد'), ('9', 'حکیم'), ('10', 'عضو جامعه'), ('11', 'شورای مرکزی'), ('12', 'مراجعین مطب'), ('13', 'مدیر کل'), ('14', 'عمومی'), ('15', 'خصوصی')], default='14', max_length=2, verbose_name='مخاطبین')),
                ('topic', models.CharField(max_length=200, verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='متن اطلاعیه')),
                ('classification', models.CharField(choices=[('1', 'عادی'), ('2', 'مهم'), ('3', 'بسیار مهم')], default=1, max_length=15, verbose_name='طبقه بندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اعلان')),
                ('user', models.ForeignKey(blank=True, help_text='اگر نوع اطلاعیه شخصی باشد نیاز است کاربر مخاطب مشخص شود', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مخاطب')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها',
                'ordering': ('created_at',),
            },
        ),
    ]
