# Generated by Django 3.2.8 on 2022-03-02 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0018_alter_profilecompletionpoints_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'طبقه بندی',
                'verbose_name_plural': 'طبقه بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf_type', models.CharField(choices=[('1', 'شخصی'), ('2', 'عمومی'), ('3', 'اختصاصی')], default='2', max_length=2, verbose_name='نوع')),
                ('topic', models.CharField(max_length=200, verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='متن اطلاعیه')),
                ('send_notif', models.BooleanField(default=True, verbose_name='ارسال نوتیفیکیشن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اعلان')),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informs.classification')),
                ('roles', models.ManyToManyField(blank=True, help_text='اگر نوع اطلاعیه اختصاصی است  ، نقش های مورد نظر را انتخاب کنید', to='accounts.Role', verbose_name='نقش های مخاطب اطلاعیه')),
                ('user', models.ForeignKey(blank=True, help_text='اگر نوع اطلاعیه شخصی باشد نیاز است کاربر مخاطب مشخص شود', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مخاطب')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها ',
                'ordering': ('created_at',),
            },
        ),
    ]
