# Generated by Django 3.2.8 on 2021-11-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_is_expert'),
        ('informs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inform',
            name='recipients',
        ),
        migrations.AddField(
            model_name='inform',
            name='role',
            field=models.ManyToManyField(blank=True, help_text='اگر نوع اطلاعیه اختصاصی است ، نقش های مورد نظر را انتخاب کنید', to='accounts.Role'),
        ),
        migrations.AddField(
            model_name='inform',
            name='type',
            field=models.CharField(choices=[('1', 'شخصی'), ('2', 'عمومی'), ('3', 'اختصاصی')], default='2', max_length=2, verbose_name='نوع'),
        ),
    ]
