# Generated by Django 3.2.8 on 2022-03-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inform',
            old_name='classification',
            new_name='inf_classification',
        ),
    ]
