# Generated by Django 3.2.8 on 2022-03-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informs', '0002_rename_classification_inform_inf_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='inf_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informs.classification', verbose_name='طبقه بندی'),
        ),
    ]
