# Generated by Django 3.2.8 on 2021-11-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_is_expert'),
        ('informs', '0002_auto_20211123_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inform',
            old_name='type',
            new_name='inf_type',
        ),
        migrations.RemoveField(
            model_name='inform',
            name='role',
        ),
        migrations.AddField(
            model_name='inform',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='اگر نوع اطلاعیه اختصاصی است ، نقش های مورد نظر را انتخاب کنید', to='accounts.Role', verbose_name='نقش های مخاطب اطلاعیه'),
        ),
    ]
