# Generated by Django 3.2.8 on 2022-03-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informs', '0003_alter_inform_inf_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ('name',), 'verbose_name': 'طبقه بندی', 'verbose_name_plural': 'طبقه بندی ها'},
        ),
    ]
