# Generated by Django 3.2.8 on 2021-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WpComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_post_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('comment_author', models.TextField(null=True)),
                ('comment_author_email', models.CharField(max_length=100, null=True)),
                ('comment_author_url', models.CharField(max_length=200, null=True)),
                ('comment_author_ip', models.CharField(db_column='comment_author_IP', max_length=100, null=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_date_gmt', models.DateTimeField(auto_now=True, null=True)),
                ('comment_content', models.TextField(null=True)),
                ('comment_karma', models.IntegerField(null=True)),
                ('comment_approved', models.CharField(max_length=20, null=True)),
                ('comment_agent', models.CharField(max_length=255, null=True)),
                ('comment_type', models.CharField(max_length=20, null=True)),
                ('comment_parent', models.PositiveBigIntegerField(null=True)),
                ('user_id', models.PositiveBigIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Wp Comment',
                'verbose_name_plural': 'Wp Comments',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WpPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.PositiveBigIntegerField(blank=True, null=True)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('post_date_gmt', models.DateTimeField(blank=True, null=True)),
                ('post_content', models.TextField(blank=True, null=True)),
                ('post_title', models.TextField(blank=True, null=True)),
                ('post_excerpt', models.TextField(blank=True, null=True)),
                ('post_status', models.CharField(blank=True, max_length=20, null=True)),
                ('comment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ping_status', models.CharField(blank=True, max_length=20, null=True)),
                ('post_password', models.CharField(blank=True, max_length=255, null=True)),
                ('post_name', models.CharField(blank=True, max_length=200, null=True)),
                ('to_ping', models.TextField()),
                ('pinged', models.TextField()),
                ('post_modified', models.DateTimeField(blank=True, null=True)),
                ('post_modified_gmt', models.DateTimeField(blank=True, null=True)),
                ('post_content_filtered', models.TextField(blank=True, null=True)),
                ('post_parent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_order', models.IntegerField(blank=True, null=True)),
                ('post_type', models.CharField(blank=True, max_length=20, null=True)),
                ('post_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wp Post',
                'verbose_name_plural': 'Wp Posts',
                'ordering': ('id',),
            },
        ),
    ]
