# Generated by Django 3.2.8 on 2022-03-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import wphome.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wphome.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=wphome.models.upload_image_location, verbose_name='تصویر پست')),
                ('file', models.FileField(blank=True, null=True, upload_to=wphome.models.upload_audo_file_location, verbose_name='فایل صوتی')),
                ('short_description', models.TextField(verbose_name='خلاصه مطلب')),
                ('share_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='لینک اشتراک گذاری')),
                ('push_notif_description', models.TextField(verbose_name='توضیح مختصر پوش نوتیفیکیشن')),
                ('push_notif_thumbnail', models.ImageField(blank=True, null=True, upload_to=wphome.models.upload_thumbnail_location, verbose_name='تصویر پوش نوتیفیکیشن')),
                ('link_tv', models.URLField(blank=True, help_text='اگر پست از نوع احیا تی وی بود لینک آن اینجا درج شود.', null=True, verbose_name='لینک احیا تی وی')),
                ('radio_ehya', models.BooleanField(default=False, verbose_name='رادیو احیا')),
                ('ehya_tv', models.BooleanField(default=False, verbose_name='احیا تی وی')),
                ('special_post', models.BooleanField(default=False, verbose_name='پست ویژه')),
                ('send_push', models.BooleanField(default=True, verbose_name='ارسال پوش نوتیفیکیشن')),
                ('status', models.CharField(choices=[('1', 'منتشر شده'), ('2', 'عدم انتشار'), ('3', 'برای بازبینی'), ('4', 'پیش نویس'), ('5', 'در صف انتشار')], max_length=1, null=True, verbose_name='وضعیت')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_to_publish', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('categories', models.ManyToManyField(to='wphome.Category', verbose_name='دسته بندی')),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='غلاقه مندی')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک ها')),
                ('tags', models.ManyToManyField(blank=True, to='wphome.Tag', verbose_name='برچسب ها')),
                ('views', models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='بازدید کنندگان')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('point_gained', models.BooleanField(default=False, verbose_name='امتیاز کسب شده')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wphome.comment', verbose_name='کامنت والد')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wphome.post', verbose_name='پست مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
