# Generated by Django 3.2.8 on 2022-03-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(null=True, verbose_name='متن کامل مطلب'),
        ),
    ]
