# Generated by Django 3.2.8 on 2021-12-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wpcomments',
            options={'ordering': ('comment_date',), 'verbose_name': 'Wp Comment', 'verbose_name_plural': 'Wp Comments'},
        ),
        migrations.AlterModelOptions(
            name='wpposts',
            options={'ordering': ('post_date',), 'verbose_name': 'Wp Post', 'verbose_name_plural': 'Wp Posts'},
        ),
    ]
