# Generated by Django 3.2.8 on 2022-03-15 07:36

from django.db import migrations, models
import wphome.models


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0002_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد رنگ 1'),
        ),
        migrations.AddField(
            model_name='category',
            name='code_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد رنگ 1'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=wphome.models.upload_icon_location, verbose_name='آیکون'),
        ),
    ]
