# Generated by Django 3.2.8 on 2022-01-19 20:44

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import wphome.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wphome', '0003_auto_20220118_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wphome.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=wphome.models.upload_image_location, verbose_name='تصویر پست')),
                ('file', models.FileField(upload_to=wphome.models.upload_audo_file_location, verbose_name='فایل صوتی')),
                ('short_description', models.TextField(verbose_name='خلاصه مطلب')),
                ('link_tv', models.URLField(blank=True, help_text='اگر پست از نوع احیا تی وی بود لینک آن اینجا درج شود.', null=True, verbose_name='لینک احیا تی وی')),
                ('radio_ehya', models.BooleanField(default=False, verbose_name='رادیو احیا')),
                ('ehya_tv', models.BooleanField(default=False, verbose_name='احیا تی وی')),
                ('published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wphome.category', verbose_name='دسته بندی')),
                ('tag', models.ManyToManyField(blank=True, to='wphome.Tag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پسبت ها',
                'ordering': ('date_published',),
            },
        ),
    ]
