# Generated by Django 3.2.8 on 2022-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0003_auto_20220315_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text_color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد رنگ متن'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد رنگ 2'),
        ),
    ]
