# Generated by Django 3.2.8 on 2022-01-19 20:58

from django.db import migrations, models
import wphome.models


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0004_category_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=wphome.models.upload_audo_file_location, verbose_name='فایل صوتی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=wphome.models.upload_image_location, verbose_name='تصویر پست'),
        ),
    ]
