# Generated by Django 3.2.8 on 2022-01-20 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wphome', '0005_auto_20220120_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=5, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'امتیاز ثبت کامنت',
                'verbose_name_plural': 'امتیاز ثبت کامنت',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date_published',), 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wphome.comment')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wphome.post', verbose_name='پست مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
