# Generated by Django 3.2.8 on 2022-02-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0007_auto_20220121_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='send_push',
            field=models.BooleanField(default=True, verbose_name='ارسال پوش نوتیفیکیشن'),
        ),
        migrations.AddField(
            model_name='post',
            name='special_post',
            field=models.BooleanField(default=False, verbose_name='پست ویژه'),
        ),
    ]
