# Generated by Django 3.2.8 on 2022-02-04 11:15

from django.db import migrations, models
import wphome.models


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0011_auto_20220204_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='push_notif_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=wphome.models.upload_thumbnail_location, verbose_name='تصویر پوش نوتیفیکیشن'),
        ),
    ]
