# Generated by Django 3.2.8 on 2022-02-11 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wphome', '0012_post_push_notif_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='لایک ها'),
        ),
        migrations.AddField(
            model_name='post',
            name='share_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='لینک اشتراک گذاری'),
        ),
    ]
