# Generated by Django 3.2.8 on 2022-02-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0014_searchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
