# Generated by Django 3.2.8 on 2022-03-04 11:00

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0016_auto_20220302_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='point_gained',
            field=models.BooleanField(default=False, verbose_name='امتیاز کسب شده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wphome.comment', verbose_name='کامنت والد'),
        ),
    ]
