# Generated by Django 3.2.8 on 2022-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0018_post_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'منتشر شده'), ('2', 'عدم انتشار'), ('3', 'برای بازبینی'), ('4', 'پیش نویس')], max_length=1, null=True, verbose_name='وضعیت'),
        ),
    ]
