# Generated by Django 3.2.8 on 2022-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0020_auto_20220304_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_to_publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
