# Generated by Django 3.2.8 on 2022-03-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0021_alter_post_date_to_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='wphome.Category', verbose_name='دسته بندی'),
        ),
    ]
