# Generated by Django 3.2.8 on 2022-03-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0022_auto_20220305_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
