# Generated by Django 3.2.8 on 2022-03-05 20:54

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0023_rename_category_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wphome.category', verbose_name='والد'),
        ),
    ]
