# Generated by Django 3.2.8 on 2022-03-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wphome', '0024_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
