"""
Django settings for ehyasalamat project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from datetime import timedelta
import locale
from pathlib import Path
import firebase_admin
from decouple import config
from firebase_admin import credentials

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xo-4@#gl^ose#qf=)0*0^u58gk9$^@55t8noom^ny60&qymn72'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    # 'jet.dashboard',
    # 'jet',
    # 'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'ticket.apps.TicketConfig',
    'informs.apps.InformsConfig',
    'sms.apps.SmsConfig',
    'treasure.apps.TreasureConfig',
    'support.apps.SupportConfig',
    'wphome.apps.WphomeConfig',
    'push_notification.apps.PushNotificationConfig',
    'jalali_date',
    'mptt',
    "fcm_django",
    # swagger
    'drf_yasg',
    # api
    'rest_framework',

    'rangefilter',

    # cors
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ehyasalamat.urls'

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True

locale.setlocale(locale.LC_ALL, "fa_IR.UTF-8")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ehyasalamat.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGES = (
#     ('fa', 'Farsi'),
# )

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = "accounts.User"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# STATICFILES_DIRS = [BASE_DIR / 'assets']
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1)
}

JALALI_DATE_DEFAULTS = {
    'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',
            # OR
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
            # 'admin/js/main.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}

CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# JET_THEMES = [
#     {
#         'theme': 'default', # theme folder name
#         'color': '#47bac1', # color of the theme's button in user menu
#         'title': 'Default' # theme title
#     },
#     {
#         'theme': 'green',
#         'color': '#44b78b',
#         'title': 'Green'
#     },
#     {
#         'theme': 'light-green',
#         'color': '#2faa60',
#         'title': 'Light Green'
#     },
#     {
#         'theme': 'light-violet',
#         'color': '#a464c4',
#         'title': 'Light Violet'
#     },
#     {
#         'theme': 'light-blue',
#         'color': '#5EADDE',
#         'title': 'Light Blue'
#     },
#     {
#         'theme': 'light-gray',
#         'color': '#222',
#         'title': 'Light Gray'
#     }
# ]

DATA_UPLOAD_MAX_MEMORY_SIZE = 9015165

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AAAAAGu1Y9U:APA91bG02jabxP5bpUbh8penpC8HVOp9Y0PcKicrPAEz3akhcDdoAn73ZmVUzO3kaBz25eE8qtcR81TbETFrmOHAftc69DqYKfQ1neq1xLxhh-UL0mNf7tir85xfulrJnTNxx4HLePM4",
    "ONE_DEVICE_PER_USER": False,
    "DELETE_INACTIVE_DEVICES": False,
}
cert = {
    "type": "service_account",
    "project_id": "nephalemapp-56712",
    "private_key_id": "9d5e31ffbe7208709cc47ee346702a657f847bae",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC6FRUDR3QTKtaR\nbyQNLMmgeHzcCDmuT6bzauX9Z0y4p2iWhj65EDNDdsdhDgg4wV+DsbaRnRizkmGM\nGJ/j7Cj44PwyuTzQ/n8crIw1qO2i0RxMmaVLzaYMyczU40dDZEBaxog13uCrosWO\nYVdHf+1C2RoBuOrkw9TI7drAORXApa8k+mfITZd31fEbOx98ilFN/9LsIAWChDpY\nNq0d3jtWKOPpgLI+As+QL4qN8kCMbTncPQ8GviLvbjrkPwtbHZJ0aJajvfmZ9jjj\nqsuVw6AauBm4QBifJvQx+mqDqRx6JZqnvhQNb3WxGdCJ/+CB7FFT1100ArLKEZag\n9/KCOZ7rAgMBAAECggEARVY9si8ZzVqVATQMluwtZSIARGy8MXt0lhcrA7VOHTAk\nBJKZJJQoxeaofD2iSqOjV4sMoE2NOrw8pNs4GNGSosoSr0PeqXFrI+AXjpcXlSee\nB9zofspuKS24qUrW7wGYCTsY3hniVZIdUuRqhTXhzpre2e1xeTSPQR9/90hOFq4C\nm9x4gV3Gw05omaKKoPEg/9JkhWiahMCmyU512cF1KJBz4fumykWQ1BWWKo1lKxdO\npcMwx/Nour9BiakZV36IZMxjkZdL2vGmvdcWquYXQ+qn3LTkVQpsEW1ZXBf0xVNn\nyiBcPo0o5lGRVOEP0Bu9CZWfIVkrU/iSsUQ4Qxq1gQKBgQDwk9WqgePjQDFVd0f+\nUVJqmAwRsRtLjpJ/m3gq4coVOxXT9BHhivxbTR6FoxSjVh9tX/cynLQszxq9lijZ\nsamsPTdSYswxaK8OzddPCa3qwqaDj92W0FHCBoobc4enoBAUYYCJ1rOBB7ljpmiN\nYipB6DLU5d5qNDiL04TadeuLmwKBgQDGAuq+DXG2OAITxw53jk7m6RMd8jYVBE6I\nGpOphgN4kQPAjefTR2v7pVTtRA+6DovszfBVUMsY0vXO+wgy6eeilb4oOMeKXCjU\nS8ZFuFuhMfk51AzJEtGpeF7go4LGBTsrI2SDOPEh3uYnIQohK3ZGjF1H8voCFZOI\nFB4p9eG28QKBgQDZtT7XVUIQBahfalk5OQh3M+9AF2DXCEdkuSGO1NNWUSjYrPd9\nfpQOX4SudL0Zbrdz+DMwlwSpxCWzyW5gSll8Z81nfcbBM7WvlPEyMlUzrECZsBhc\nAVrrVZWnb+4j8EJ83xs+IZBBxOas2gulXl9VUzak2Pxkaat+RcTlGW813wKBgQCS\nN1E0KiVP0yflhtXt/s3QwUd2k4bQGjALXOSxB97ERwEoTSFk6Jaaakm+MsYSM++r\nW58ewNxYZl9RChnRzttXOZADj3n5d3hG2/V7QlmXPJm21Bjk2dqsc9BLvTIyG2bH\nwgjUxVV6F2iIeGNMfxWFnty65ncq1tfsYj6r6X9VYQKBgQC3g2ZI0HQynjJf3em/\nr0CvtRQw31hSOvTHk/Jpgh1So8kh+GcUQu1lhxE9ojmuitzwnqjaSzpNxSEN9IJR\nHa5aaYRVOeTBivq3ldBnRKjnsLzsVSUAksz4oIlysauddjYKYoBeBlW9JdYWIRXa\nVcsUBaoLXizu8pmJ8wHEWMp0Aw==\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-adminsdk-6uram@nephalemapp-56712.iam.gserviceaccount.com",
    "client_id": "102698689366543959734",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-6uram%40nephalemapp-56712.iam.gserviceaccount.com"
}

cred = credentials.Certificate(cert=cert)
firebase_admin.initialize_app(cred)
