# Generated by Django 3.2.8 on 2022-03-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بخش')),
            ],
            options={
                'verbose_name': 'بخش سلامت',
                'verbose_name_plural': 'بخش های سلامت',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='عنوان')),
                ('request_text', models.TextField(blank=True, verbose_name='متن درخواست')),
                ('file', models.FileField(blank=True, null=True, upload_to=ticket.models.upload_location, verbose_name='فایل ضمیمه')),
                ('status_for_user', models.CharField(choices=[('1', 'در حال بررسی'), ('2', 'پاسخ داده شده'), ('3', 'بسته شده')], default=1, max_length=1, verbose_name='وضعیت برای کاربر')),
                ('status_for_expert', models.CharField(choices=[('1', 'جدید'), ('2', 'ارجاء به کارشناس ارشد'), ('3', 'پاسخ داده شده'), ('4', 'بسته شده'), ('5', 'پاسخ کاربر')], default=1, max_length=1, verbose_name='وضعیت برای کارشناس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.section', verbose_name='بخش مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
                ('file', models.FileField(blank=True, null=True, upload_to=ticket.models.answer_upload_location, verbose_name='فایل ضمیمه')),
                ('status', models.CharField(choices=[('1', 'دیده شده'), ('2', 'دیده نشده')], default=2, max_length=1, verbose_name='وضعیت')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دیده شدن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket', verbose_name='تیکت مربوطه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
                'ordering': ('created_at',),
            },
        ),
    ]
