# Generated by Django 3.2.8 on 2022-04-18 05:56

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=ticket.models.channel_icon_upload_location, verbose_name='آیکون')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('link', models.CharField(max_length=255, verbose_name='لینک')),
                ('back_ground_colour_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ بک گراند 1')),
                ('back_ground_colour_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ بک گراند 2')),
            ],
            options={
                'verbose_name': 'گروه و کانال',
                'verbose_name_plural': 'گروه ها و کانال ها',
                'ordering': ('title',),
            },
        ),
    ]
