# Generated by Django 3.2.8 on 2021-10-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='seen',
        ),
        migrations.AddField(
            model_name='answer',
            name='seen_admin',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر'),
        ),
        migrations.AddField(
            model_name='answer',
            name='seen_user',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط ادمین'),
        ),
    ]
