# Generated by Django 3.2.8 on 2021-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20211021_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='seen_admin',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='seen_user',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر'),
        ),
    ]
