# Generated by Django 3.2.8 on 2021-11-03 21:48

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20211021_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='seen_admin',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='seen_user',
        ),
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ticket.models.answer_upload_location, verbose_name='فایل ضمیمه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ticket.models.upload_location, verbose_name='فایل ضمیمه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='section',
            field=models.CharField(blank=True, choices=[('1', 'قلب و عروق'), ('2', 'اطفال'), ('3', 'زنان و نازایی'), ('4', 'پوست ، مو و زیبایی'), ('5', 'گوش ، حلق و بینی'), ('6', 'ارتوپدی'), ('7', 'غدد')], max_length=2, verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('1', 'جدید'), ('2', 'در حال بررسی'), ('3', 'پاسخ داده شده'), ('4', 'بسته شده')], default=1, max_length=1, verbose_name='وضعیت'),
        ),
    ]
