# Generated by Django 3.2.8 on 2021-11-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20211104_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPointCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0, help_text='مقدار هزینه امتیاز جهت طرح پرسش توسط کاربر', verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'هزینه پرسش',
                'verbose_name_plural': 'هزینه پرسش',
            },
        ),
    ]
