# Generated by Django 3.2.8 on 2021-11-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20211104_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='section',
            field=models.CharField(blank=True, choices=[('1', 'قلب و عروق'), ('2', 'اطفال'), ('3', 'زنان و نازایی'), ('4', 'پوست ، مو و زیبایی'), ('5', 'گوش ، حلق و بینی'), ('6', 'ارتوپدی'), ('7', 'غدد')], max_length=2, verbose_name='بخش مربوطه'),
        ),
    ]
