# Generated by Django 3.2.8 on 2021-11-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.section', verbose_name='بخش مربوطه'),
        ),
    ]
