# Generated by Django 3.2.8 on 2021-12-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_ticketanswerlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('1', 'دیده شده'), ('2', 'دیده نشده')], default=1, max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status_for_expert',
            field=models.CharField(choices=[('1', 'جدید'), ('2', 'ارجاء به کارشناس ارشد'), ('3', 'پاسخ داده شده'), ('4', 'بسته شده'), ('5', 'پاسخ کاربر')], default=1, max_length=1, verbose_name='وضعیت برای کارشناس'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status_for_user',
            field=models.CharField(choices=[('1', 'در حال بررسی'), ('2', 'پاسخ داده شده'), ('3', 'بسته شده')], default=1, max_length=1, verbose_name='وضعیت برای کاربر'),
        ),
    ]
