# Generated by Django 3.2.8 on 2021-12-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20211212_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دیده شدن'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('1', 'دیده شده'), ('2', 'دیده نشده')], default=2, max_length=1, verbose_name='وضعیت'),
        ),
    ]
